language: node_js
node_js:
  - node
sudo: false
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: XUirjHTHTGwuudTDOhgv7LWq8n7uTsy/W5/jIaJsKUTd0Izlw9HHIJSXROQqNiDzkVqiuNywLCqreIjX4fpudQIsZLEAqFkbFpi9kFbwdTIDkg6UEZc5BONf8p7nYLewEnD5kUXAOCgsf/DHUwnQqBrbbZnuV/g7wyMkOUhf2f/XAPbF3kHuFaX3Q7FcORbcoyull2BDG7mZvjTaZ7avVPEvUtcMiG+fjjtzAEN8NzSvj1hmqdJqGnpws4A2q6lVXteonWTAL/XHYt1HwVH2qQP4UEsG1ANuoI/Zi1HWuKvRRP3dN65SjU4SN9IrKhuh21RJmk8SEOlgEp++wUjjn1ED4m7v2j3uUqEFbO7761GAQZhaehCaAoGQCWeJUehPgE4b8+PUJTSQ3SPp78D2/9kTJaY1go6YziSxMJ236PSjUhnk+8VIdcLndiOP4oWco8hQ60MrTlLMgyqGexIyRGnZc5Q9icdQ3d12xRmck8Aloqwt8HaQGM/uaF8WJHWNG5yTgdc5p0Nro/VyNzdM3z2aMEJUZXgWahnkGwCBpgJJvcX+Q1sqK2l+WKvOFh0YCU5JDM5BkSfNoEiBsDCZZjoUNoHSj8ciR0jaAZXsRA4/90Vt4rmHLStjmh1Hpmw+5Ky1ZVsxc/acuCjDAGY/tnK7jqAaUYkXQvi9QN2XHS0=
  on:
    branch: main